name: task_manager
description: A new Flutter project.
publish_to: "none"
version: 0.1.2

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  dartz: ^0.10.1
  dotted_border: ^2.0.0+3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  get_it: ^7.3.0
  path_provider: ^2.0.15
  sqflite: ^2.2.8+2
  timeline_tile: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
